### ISSUE TITLE
Sheep not standing on boxes?

### ISSUE THREAD

**Issue by minimos11** [Adrianotiger/web-esheep#34]
The sheep don't want to stand on the boxes I create but they do stand on hr tags.
I have tried to copy one of you div boxes in your examples to see if it would work but that didn't work.

So what does the js check for to see if it is a box?

**Comment by Adrianotiger** [comment]
The sheep should stay on div's and hr elements. The div should be static on the page and not created dynamically. Be sure the sheep is created, after the page was loaded.

**Comment by minimos11** [comment]
Thank you! The problem was caused by the sheep being spawned before page load.
I fixed it by using defer in the script tag for the start Esheep.
